const actions = {
  "GET_ALL_CUSTOMERS": "GET_ALL_CUSTOMERS",
  "GET_ALL_PRODUCTS": "GET_ALL_PRODUCTS",
  "GET_DELIVERY_ADDER": "GET_DELIVERY_ADDER",
  "GET_CUSTOMER_ADDER": "GET_CUSTOMER_ADDER",
  "GET_CUSTOMER_VARIANCE": "GET_CUSTOMER_VARIANCE"
};

export default actions;
